[toolchain]
# powerfmt v0.2.0 requires rustc 1.67.0
# time-core v0.1.2 requires rustc 1.67.0
# nix v0.28.0 requires rustc 1.69 (cargo-tarpaulin)
# home v0.5.9 requires rustc 1.70.0
# clap_lex v0.7.1 requires rustc 1.74
# error: unsupported output in build script of `cargo-tarpaulin v0.30.0`: `cargo::rustc-check-cfg=cfg(ptrace_supported)` requires rustc 1.77.0
channel = "1.65.0"
components = ["clippy", "rustfmt"]
